language: php

branches:
    only:
        - master
        - /^release\/.+$/

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

env:
    - dependencies=highest
    - dependencies=lowest

matrix:
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache

install:
    - if [ "$dependencies" = "lowest" ]; then composer update --no-interaction --no-suggest --prefer-lowest --prefer-dist; fi;
    - if [ "$dependencies" = "highest" ]; then composer update --no-interaction --no-suggest --prefer-dist; fi;

script: 'true'

notifications:
    webhooks:
        urls:
            - https://zeus.ci/hooks/23e1f6e8-2e98-11e9-a263-0a580a28120c/public/provider/travis/webhook
        on_success: always
        on_failure: always
        on_start: always
        on_cancel: always
        on_error: always
