name: Continuous Integration

on:
  pull_request: null
  push:
    branches:
      - master

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      SYMFONY_REQUIRE: ${{ matrix.symfony-version }}
    strategy:
      fail-fast: false
      matrix:
        php:
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
        symfony-version:
          - 3.4.*
          - 4.4.*
          - 5.*
          - 6.*
          - 7.*
        dependencies:
          - highest
        exclude:
          - php: '7.2'
            symfony-version: 6.*
            dependencies: highest
          - php: '7.3'
            symfony-version: 6.*
            dependencies: highest
          - php: '7.4'
            symfony-version: 6.*
            dependencies: highest
          - php: '7.2'
            symfony-version: 7.*
            dependencies: highest
          - php: '7.3'
            symfony-version: 7.*
            dependencies: highest
          - php: '7.4'
            symfony-version: 7.*
            dependencies: highest
          - php: '8.0'
            symfony-version: 7.*
            dependencies: highest
          - php: '8.1'
            symfony-version: 7.*
            dependencies: highest
        include:
          - php: '7.2'
            symfony-version: 3.4.*
            dependencies: lowest
          - php: '7.2'
            symfony-version: 4.4.*
            dependencies: lowest
          - php: '7.2'
            symfony-version: 5.*
            dependencies: lowest
          - php: '8.0'
            symfony-version: 6.*
            dependencies: lowest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: flex

      - name: Install dependencies
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: --prefer-dist
